replicaCount: 2

image:
  repository: ghcr.io/huseinj/profile
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: hjusic.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: profile-tls
      hosts:
        - hjusic.com

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
